package in.westerncoal.biometric.types;

public enum MessageType {
	DEVICE_INIT_REGISTER_MSG,
	DEVICE_SENDLOG_MSG,
	DEVICE_SENDUSER_MSG,
	DEVICE_GETALLLOG_REPLY_MSG,
	UNKNOWN_MSG, DEVICE_GETALLLOG_MSG, DEVICE_INIT_REGISTER_REPLY_MSG, DEVICE_GETALLLOG_REPLY_RESPONSE_MSG
}
